// flow-typed signature: 2fdfc8475bc6406dc069caf9e5a3cd55
// flow-typed version: <<STUB>>/lattice-sagas_v~0.53.0/flow_v0.129.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice-sagas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice-sagas' {
  declare module.exports: any;
}
