// flow-typed signature: ec8884b3aa718752239a929258e6486c
// flow-typed version: <<STUB>>/papaparse_v5.3.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'papaparse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'papaparse' {
  declare module.exports: any;
}
