const PROFILE = 'profile';
const SURVEY_HISTORY = 'surveyHistory';
const GREATEST_NEEDS = 'greatestNeeds';
const SELF_SUFFICIENCY = 'selfSufficiency';

const PROFILE_PATHS = {
  [SURVEY_HISTORY]: [PROFILE, SURVEY_HISTORY],
  [GREATEST_NEEDS]: [PROFILE, GREATEST_NEEDS],
  [SELF_SUFFICIENCY]: [PROFILE, SELF_SUFFICIENCY],
};

export {
  PROFILE,
  SURVEY_HISTORY,
  GREATEST_NEEDS,
  SELF_SUFFICIENCY,
  PROFILE_PATHS,
};
